### ISSUE TITLE
Unable to set custom font

### ISSUE THREAD

**Issue by git58** [dracula/github#19]
I have various installed fonts on my Arch Linux PC. Set custom font to "FiraCode" or "JetBrainsMono Nerd Font Mono" has no effect. I successfully applied this fonts in other extensions for Vivaldi browser, but not in Dracula Github style for Stylish. What goes wrong?

I change default style settings to this:

```css
@var checkbox purple-logo "Use purple logo" 1
@var checkbox purple-topbar "Use purple topbar" 1
@var checkbox colored-status "Use dracula colors on status badges" 1
@var checkbox black-btn-text "Use black text on colored buttons" 1
@var checkbox contributor-graph-colors "Use dracula colors for profile contributor graphs" 1

@var checkbox custom-font-enabled "Use custom code font" 1
@var text custom-font "Custom Font" "JetBrainsMono Nerd Font Mono Regular"
```

**Comment by moeshin** [comment]
It works for me

```css
  .react-code-text, .comment-body pre {
    if custom-font-enabled {
      font-family: custom-font;
    }
  }
  
  #read-only-cursor-text-area {
    if custom-font-enabled {
      font-family: custom-font !important;
    }
  }
```
