### ISSUE TITLE
Theme is partially broken

### ISSUE THREAD

**Issue by sanriodev** [dracula/github#28]
Hello,

The theme is partially broken since 26th march of 2025.

This can be seen in the contribution Graph.

![Image](https://github.com/user-attachments/assets/3b804557-3d3b-4bfb-9065-dbab777ef9e0)

When I will find time to do so, I will open a PR.

Kind regards :)

EDIT: I'm sorry looks like I can't fix a pr.

The github css rules changed. The fix is changing:

```css
    if contributor-graph-colors {
      --color-calendar-graph-day-bg: #44475a;
      --color-calendar-graph-day-L1-bg: #6272a4;
      --color-calendar-graph-day-L2-bg: #8be9fd;
      --color-calendar-graph-day-L3-bg: #bd93f9;
      --color-calendar-graph-day-L4-bg: #ff79c6;
    }
```
to
```css
    if contributor-graph-colors {
      --contribution-default-bgColor-0: #44475a;
      --contribution-default-bgColor-1: #6272a4;
      --contribution-default-bgColor-2: #8be9fd;
      --contribution-default-bgColor-3: #bd93f9;
      --contribution-default-bgColor-4: #ff79c6;
    }
```
